AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  heartland-taxservice

  Sample SAM Template for heartland-taxservice
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:

  TaxServiceAWSApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: TaxServiceApiGateway
      StageName: Prod
      Cors:
        AllowMethods: "'*'"
        AllowHeaders: "'*'"
        AllowOrigin: "'www.example.com'"
        MaxAge: "'600'"
        AllowCredentials: true

  HeartlandTaxServiceFunction:
    Type: AWS::Serverless::Function
    Properties:
      Policies:
        - 
          SSMParameterReadPolicy:
            ParameterName: TAX_JAR_API_KEY_SB
      PackageType: Image
      Architectures:
        - x86_64
      Events:
        CalculateSalesTax:
          Type: Api
          Properties:
            RestApiId: !Ref TaxServiceAWSApiGateway
            Path: /tax-service/calculate-sales-tax
            Method: post

    Metadata:
      DockerTag: nodejs12.x-v1
      DockerContext: ./heartland-tax-service
      Dockerfile: Dockerfile

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  TaxServiceApi:
    Description: "API Gateway endpoint URL for Prod stage for Tax Service function"
    Value: !Sub "https://${TaxServiceAWSApiGateway}.execute-api.${AWS::Region}.amazonaws.com/tax-service/"
  HeartlandTaxServiceFunction:
    Description: "Tax Service Lambda Function ARN"
    Value: !GetAtt HeartlandTaxServiceFunction.Arn
  HeartlandTaxServiceFunctionIamRole:
    Description: "Implicit IAM Role created for Tax Service function"
    Value: !GetAtt HeartlandTaxServiceFunctionRole.Arn
