version = 0.1
[default]
[default.pipeline_bootstrap]
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::464570369687:user/aws-sam-cli-managed-dev-pipeline-reso-PipelineUser-1K3HIAYH8O2FP"

[dev]
[dev.pipeline_bootstrap]
[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::464570369687:role/aws-sam-cli-managed-dev-pipe-PipelineExecutionRole-16RVKO412DSDR"
cloudformation_execution_role = "arn:aws:iam::464570369687:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionR-1SRU4EPZCXMC"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-artifactsbucket-1bmu12m7hugcg"
image_repository = "464570369687.dkr.ecr.us-east-1.amazonaws.com/aws-sam-cli-managed-dev-pipeline-resources-imagerepository-7cma5yxsf93b"
region = "us-east-1"

[prod]
[prod.pipeline_bootstrap]
[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::464570369687:role/aws-sam-cli-managed-prod-pip-PipelineExecutionRole-8DZ78T1O4QGZ"
cloudformation_execution_role = "arn:aws:iam::464570369687:role/aws-sam-cli-managed-prod-CloudFormationExecutionR-G9OSMFWM1TU2"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline-artifactsbucket-1c8rct2ohvhdv"
image_repository = "464570369687.dkr.ecr.us-east-1.amazonaws.com/aws-sam-cli-managed-prod-pipeline-resources-imagerepository-yphixrqmquzp"
region = "us-east-1"
